//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDMaker.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IDMaker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 110000	北京市
        ///110101	东城区
        ///110102	西城区
        ///110105	朝阳区
        ///110106	丰台区
        ///110107	石景山区
        ///110108	海淀区
        ///110109	门头沟区
        ///110111	房山区
        ///110112	通州区
        ///110113	顺义区
        ///110114	昌平区
        ///110115	大兴区
        ///110116	怀柔区
        ///110117	平谷区
        ///110118	密云区
        ///110119	延庆区
        ///120000	天津市
        ///120101	和平区
        ///120102	河东区
        ///120103	河西区
        ///120104	南开区
        ///120105	河北区
        ///120106	红桥区
        ///120110	东丽区
        ///120111	西青区
        ///120112	津南区
        ///120113	北辰区
        ///120114	武清区
        ///120115	宝坻区
        ///120116	滨海新区
        ///120117	宁河区
        ///120118	静海区
        ///120119	蓟州区
        ///130000	河北省
        ///130100	石家庄市
        ///130102	长安区
        ///130104	桥西区
        ///130105	新华区
        ///130107	井陉矿区
        ///130108	裕华区
        ///130109	藁城区
        ///130 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string StringAdminAreaCode {
            get {
                return ResourceManager.GetString("StringAdminAreaCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///  &quot;00405512&quot;: {
        ///    &quot;bank&quot;: &quot;交通银行&quot;,
        ///    &quot;bankCode&quot;: &quot;03010000&quot;,
        ///    &quot;BIN&quot;: &quot;00405512&quot;,
        ///    &quot;cardName&quot;: &quot;太平洋互连卡&quot;,
        ///    &quot;cardNoLength&quot;: &quot;17&quot;,
        ///    &quot;cardType&quot;: &quot;借记卡&quot;
        ///  },
        ///  &quot;0049104&quot;: {
        ///    &quot;bank&quot;: &quot;交通银行&quot;,
        ///    &quot;bankCode&quot;: &quot;03010000&quot;,
        ///    &quot;BIN&quot;: &quot;0049104&quot;,
        ///    &quot;cardName&quot;: &quot;太平洋信用卡&quot;,
        ///    &quot;cardNoLength&quot;: &quot;16&quot;,
        ///    &quot;cardType&quot;: &quot;贷记卡&quot;
        ///  },
        ///  &quot;0053783&quot;: {
        ///    &quot;bank&quot;: &quot;交通银行&quot;,
        ///    &quot;bankCode&quot;: &quot;03010000&quot;,
        ///    &quot;BIN&quot;: &quot;0053783&quot;,
        ///    &quot;cardName&quot;: &quot;太平洋信用卡&quot;,
        ///    &quot;cardNoLength&quot;: &quot;16&quot;,
        ///    &quot;cardType&quot;: &quot;贷记卡 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string StringBankCardInfo {
            get {
                return ResourceManager.GetString("StringBankCardInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 110000 北京市
        ///110100 北京市市辖区
        ///110101 北京市东城区
        ///110102 北京市西城区
        ///110103 北京市崇文区
        ///110104 北京市宣武区
        ///110105 北京市朝阳区
        ///110106 北京市丰台区
        ///110107 北京市石景山区
        ///110108 北京市海淀区
        ///110109 北京市门头沟区
        ///110111 北京市房山区
        ///110112 北京市通州区
        ///110113 北京市顺义区
        ///110200 北京市县
        ///110221 北京市昌平县
        ///110224 北京市大兴县
        ///110226 北京市平谷县
        ///110227 北京市怀柔县
        ///110228 北京市密云县
        ///110229 北京市延庆县
        ///120000 天津市
        ///120100 天津市市辖区
        ///120101 天津市和平区
        ///120102 天津市河东区
        ///120103 天津市河西区
        ///120104 天津市南开区
        ///120105 天津市河北区
        ///120106 天津市红桥区
        ///120107 天津市塘沽区
        ///120108 天津市汉沽区
        ///120109 天津市大港区
        ///120110 天津市东丽区
        ///120111 天津市西青区
        ///120112 天 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string StringPersonIdProvince {
            get {
                return ResourceManager.GetString("StringPersonIdProvince", resourceCulture);
            }
        }
    }
}
